<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <UseVSHostingProcess>true</UseVSHostingProcess>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <Choose>
    <When Condition="('$(VisualStudioVersion)' == '10.0' or '$(VisualStudioVersion)' == '') and '$(TargetFrameworkVersion)' == 'v3.5'">
      <ItemGroup>
        <Reference Include="Microsoft.VisualStudio.QualityTools.UnitTestFramework, Version=10.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" />
      </ItemGroup>
    </When>
  </Choose>
  <ItemGroup>
    <ProjectReference Include="..\TLCGen.Dependencies\TLCGen.DataAccess\TLCGen.DataAccess.csproj" />
    <ProjectReference Include="..\TLCGen.Dependencies\TLCGen.Dependencies\TLCGen.Dependencies.csproj" />
    <ProjectReference Include="..\TLCGen.Dependencies\TLCGen.ModelManager\TLCGen.ModelManagement.csproj" />
    <ProjectReference Include="..\TLCGen.Parts\TLCGen.Settings\TLCGen.Settings.csproj" />
    <ProjectReference Include="..\TLCGen.PluggedInItems\TLCGen.Generators.CCOL\TLCGen.Generators.CCOL.csproj" />
    <ProjectReference Include="..\TLCGen.PluggedInItems\TLCGen.Importers.TabC\TLCGen.Importers.TabC.csproj" />
    <ProjectReference Include="..\TLCGen\TLCGen.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.ConsoleRunner" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
  </ItemGroup>
</Project>