<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
	  <langVersion>latest</langVersion>
	  <Platforms>AnyCPU;x64;x86</Platforms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="AppIcon.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
</Project>