namespace TLCGen.Generators.CCOL.CodeGeneration
{
    public enum CCOLCodeTypeEnum
    {
		// REG
        RegCBeforeIncludes,
        RegCIncludes,
        RegCTop,
        RegCKwcApplication,
        RegCPreApplication,
        RegCKlokPerioden,
        RegCAanvragen,
        RegCVerlenggroen,
        RegCMaxgroen,
        RegCMaxgroenNaAdd,
        RegCWachtgroen,
        RegCMeetkriterium,
        RegCFileVerwerking,
        RegCDetectieStoring,
        RegCMeeverlengen,
        RegCRealisatieAfhandelingModules,
        RegCRealisatieAfhandelingNaModules,
        RegCRealisatieAfhandeling,
        RegCAlternatieven,
        RegCSynchronisaties,
        RegCInitApplication,
        RegCApplication,
        RegCPostApplication,
        RegCPreSystemApplication,
        RegCSystemApplication,
        RegCSystemApplication2,
        RegCPostSystemApplication,
        RegCDumpApplication,
        RegCSpecialSignals,

        // OV
        OvCIncludes,
		OvCTop,
		OvCInitOV,
		OvCInstellingen,
		OvCRijTijdScenario,
		OvCInUitMelden,
		OvCOnderMaximum,
		OvCAfkapGroen,
		OvCStartGroenMomenten,
		OvCAfkappen,
		OvCTerugkomGroen,
		OvCGroenVasthouden,
		OvCMeetkriterium,
	    OvCPrioriteitsOpties,
        OvCPrioriteitsNiveau,
	    OvCPrioriteitsToekenning,
        OvCTegenhoudenConflicten,
        OvCPostAfhandelingOV,
	    OvCPARCorrecties,
	    OvCPARCcol,
	    OvCSpecialSignals,
		OvCBottom,

        // PRIO
        PrioCIncludes,
        PrioCTop,
        PrioCInitOV,
        PrioCInstellingen,
        PrioCRijTijdScenario,
        PrioCInUitMelden,
        PrioCOnderMaximum,
        PrioCAfkapGroen,
        PrioCStartGroenMomenten,
        PrioCAfkappen,
        PrioCTerugkomGroen,
        PrioCGroenVasthouden,
        PrioCMeetkriterium,
        PrioCPrioriteitsOpties,
        PrioCPrioriteitsNiveau,
        PrioCPrioriteitsToekenning,
        PrioCTegenhoudenConflicten,
        PrioCPostAfhandelingOV,
        PrioCPARCorrecties,
        PrioCPARCcol,
        PrioCSpecialSignals,
        PrioCBottom,

        // TAB
        TabCBeforeIncludes,
	    TabCIncludes,
        TabCControlDefaults,
	    TabCControlParameters,

        // SYS
        SysHBeforeUserDefines,

        // HST
        HstCTop,
        HstCPostInitApplication,
		HstCPreApplication,
		HstCKlokPerioden,
		HstCAanvragen,
		HstCVerlenggroen,
		HstCMaxgroen,
		HstCWachtgroen,
		HstCMeetkriterium,
		HstCDetectieStoring,
		HstCMeeverlengen,
		HstCSynchronisaties,
		HstCAlternatief,
		HstCRealisatieAfhandeling,
		HstCPostApplication,
		HstCPreSystemApplication,
		HstCPostSystemApplication,
		HstCPostDumpApplication,
        HstCOVHalfstarSettings
    };
}
