<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
	  <langVersion>latest</langVersion>
	  <Platforms>AnyCPU;x64;x86</Platforms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\TLCGen.Parts\TLCGen.Settings\TLCGen.Settings.csproj" />
    <ProjectReference Include="..\TLCGen.Dependencies\TLCGen.Dependencies.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="DotNetProjects.Extended.Wpf.Toolkit" />
  </ItemGroup>
</Project>